### ISSUE TITLE
status of the rdbi-driver-oracle project

### ISSUE THREAD

**Issue by blocktator** [RDBI/rdbi-driver-oracle#3]
I am interested in the status of this repo and getting this up on rubygems. Can someone tell me who is the primary maintainer?  I am able to put time into to getting this gemified and doing regression from the DBI version, as I have plenty of code that uses the ruby OCI8 DBI.  Thanks in advance.

**Comment by pilcrow** [comment]
@jamin4jc, that's me.

**Comment by blocktator** [comment]
do you have any plans on turning this into a ruby gem?
